2024-11-29 02:55:32,505 - ERROR - Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x74e1efe37860>> raised: ModuleNotFoundError("No module named 'PyHack'")
Traceback (most recent call last):
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 136, in check_custom_error_handlers
    handler = resolver.resolve_error_handler(status_code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 732, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_project/urls.py", line 28, in <module>
    path('video_downloader/', include('video_downloader.urls')),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/urls.py", line 2, in <module>
    from .views import download_video_view
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/views.py", line 7, in <module>
    from .utils.tiktok import download_tiktok_video
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/utils/tiktok.py", line 3, in <module>
    import PyHack as pyk
ModuleNotFoundError: No module named 'PyHack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/fixups/django.py", line 100, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/fixups/django.py", line 140, in validate_models
    run_checks()
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 138, in check_custom_error_handlers
    path = getattr(resolver.urlconf_module, "handler%s" % status_code)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_project/urls.py", line 28, in <module>
    path('video_downloader/', include('video_downloader.urls')),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/urls.py", line 2, in <module>
    from .views import download_video_view
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/views.py", line 7, in <module>
    from .utils.tiktok import download_tiktok_video
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/utils/tiktok.py", line 3, in <module>
    import PyHack as pyk
ModuleNotFoundError: No module named 'PyHack'
2024-11-29 02:55:32,510 - ERROR - Signal handler <promise@0x74e1ef97a850 --> <bound method Celery._autodiscover_tasks of <Celery video_project at 0x74e1ef97fb00>>> raised: ModuleNotFoundError("No module named 'PyHack'")
Traceback (most recent call last):
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/app/base.py", line 694, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/app/base.py", line 703, in _autodiscover_tasks_from_fixups
    return self._autodiscover_tasks_from_names([
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/tasks.py", line 2, in <module>
    from .utils.fallback import fallback_download
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/utils/fallback.py", line 6, in <module>
    from .tiktok import download_tiktok_video
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/utils/tiktok.py", line 3, in <module>
    import PyHack as pyk
ModuleNotFoundError: No module named 'PyHack'
2024-11-29 02:56:51,324 - ERROR - Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x762e82b8b770>> raised: ModuleNotFoundError("No module named 'PyHack'")
Traceback (most recent call last):
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 136, in check_custom_error_handlers
    handler = resolver.resolve_error_handler(status_code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 732, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_project/urls.py", line 28, in <module>
    path('video_downloader/', include('video_downloader.urls')),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/urls.py", line 2, in <module>
    from .views import download_video_view
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/views.py", line 7, in <module>
    from .utils.tiktok import download_tiktok_video
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/utils/tiktok.py", line 3, in <module>
    import PyHack as pyk
ModuleNotFoundError: No module named 'PyHack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/fixups/django.py", line 100, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/fixups/django.py", line 140, in validate_models
    run_checks()
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 138, in check_custom_error_handlers
    path = getattr(resolver.urlconf_module, "handler%s" % status_code)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_project/urls.py", line 28, in <module>
    path('video_downloader/', include('video_downloader.urls')),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/urls.py", line 2, in <module>
    from .views import download_video_view
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/views.py", line 7, in <module>
    from .utils.tiktok import download_tiktok_video
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/utils/tiktok.py", line 3, in <module>
    import PyHack as pyk
ModuleNotFoundError: No module named 'PyHack'
2024-11-29 02:56:51,326 - ERROR - Signal handler <promise@0x762e82b86850 --> <bound method Celery._autodiscover_tasks of <Celery video_project at 0x762e82b8b110>>> raised: ModuleNotFoundError("No module named 'PyHack'")
Traceback (most recent call last):
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/app/base.py", line 694, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/app/base.py", line 703, in _autodiscover_tasks_from_fixups
    return self._autodiscover_tasks_from_names([
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/home/lofa/Downloads/Telegram Desktop/venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/tasks.py", line 2, in <module>
    from .utils.fallback import fallback_download
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/utils/fallback.py", line 6, in <module>
    from .tiktok import download_tiktok_video
  File "/home/lofa/Downloads/Telegram Desktop/video_project/video_downloader/utils/tiktok.py", line 3, in <module>
    import PyHack as pyk
ModuleNotFoundError: No module named 'PyHack'
